version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=menu_admin
      - POSTGRES_PASSWORD=0711
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: